### ISSUE TITLE
Defining UNLEASH_SERVER_API_URL with a trailing slash is not working

### ISSUE THREAD

**Issue by happypoulp** [Unleash/unleash-client-nextjs#20]
### Describe the bug

Hello,

When using `UNLEASH_SERVER_API_URL` or (`NEXT_PUBLIC_UNLEASH_SERVER_API_URL`) with a value that contains a trailing slash(e.g. "https://eu.app.unleash-hosted.com/12345/api/") calling `getDefinitions` returns:

```
{
  message: 'invalid token: expected a different token type for this endpoint'
}
```

It would be nice if we could pass an URL with a trailing slash (like it's given in the Unleash UI).

### Steps to reproduce the bug

1. Using the library with valid tokens
2. Set `UNLEASH_SERVER_API_URL` or (`NEXT_PUBLIC_UNLEASH_SERVER_API_URL`) to "https://eu.app.unleash-hosted.com/12345/api/"
3. Call `getDefinitions()`

### Expected behavior

Passing `https://eu.app.unleash-hosted.com/12345/api/` OR `https://eu.app.unleash-hosted.com/12345/api` (for retro-compat with current version) to `UNLEASH_SERVER_API_URL` or (`NEXT_PUBLIC_UNLEASH_SERVER_API_URL`) should work.

### Logs, error output, etc.

```bash
{
  message: 'invalid token: expected a different token type for this endpoint'
}
```
```


### Screenshots

_No response_

### Additional context

_No response_

### Unleash version

"@unleash/nextjs": "^0.1.0"

### Subscription type

Pro

### Hosting type

Hosted by Unleash

### SDK information (language and version)

"@unleash/nextjs": "^0.1.0"

**Comment by Tymek** [comment]
[`v0.1.2`](https://github.com/Unleash/unleash-client-nextjs/releases/tag/v0.1.2)
