### ISSUE TITLE
Doesn't work but unleash-client does; Can't use instance_id

### ISSUE THREAD

**Issue by Jax-p** [Unleash/unleash-client-nextjs#21]
### Describe the bug

I've been using `'unleash-client'` and everything works fine. Now I've switched on `@unleash/nextjs` and I can't connect to my GitLab FF API anymore.

----

## How do I set instanceId?

How/where do I set global instanceId? Working solution with `'unleash-client'`:
```js
const unleash = initialize({
      url: '....',
      instanceId: '....',
      appName: '....',
});
...
unleash.isEnabled('test'); // true!
```
I see no option for this in nextjs solution.

----

Possible feature request?   
Possibility to leave auth headers blank (without token) and use instanceId instead (GitLab FF solution)

**Comment by Tymek** [comment]
Hey 👋🏻 Thanks for reporting this.

- Node SDK (`unleash-client`) it built for server-oriented architecture
- `@unleash/nextjs` SSR/SSG is for serverless/edge. There is no long-running process, no refetch.

New ""server"" (can run anywhere) SDK is split into 3 functions:
```ts
// compose like so
flagsClient(
  evaluateFlags(
    await getDefinitions(),
    {} // context, optional in next version
  )  
).isEnabled('flag')

// equivalent to
const definitions = await getDefinitions() // or just JSON, read from file or get from elsewhere
const flags = evaluateFlags(definitions, {})
const unleash = flagsClient(flags)
unleash.isEnabled('flag')
```

I will try to make it more explicit in docs.

I'm interested in supporting GitLab API. As you can see this is in the `getDefinitions` part.

Also: metrics are not supported server-side in Next.js SDK (yet).

**Comment by Jax-p** [comment]
Thank you. I've read the code later and I understand it now. I'll take a look on GitLab solution, test it in my use-case and send PR if everything works.

**Comment by Tymek** [comment]
> Is there a situation where you'd use both token and `UNLEASH_SERVER_INSTANCE_ID`? You can always override `Authentication` with `fetchOptions` 

https://github.com/Unleash/unleash-client-nextjs/pull/27#discussion_r1118464397
To consider before releasing as latest version.

**Comment by Tymek** [comment]
`unleash-client` (Node.js) is setting `instanceId` as `UNLEASH-INSTANCEID` header. The same thing here was implemented as GET parameter @Jax-p. I can't find any detailed example of how GitLab API works. Can you check if `@unleash/nextjs@v0.1.3-alpha.0` works?

**Comment by Jax-p** [comment]
You can see some implmentations based in [Ruby in GitLabs documentation](https://docs.gitlab.com/ee/operations/feature_flags.html). We are currently using `0.1.3-alpha.0` in our project (currently dev env only) and everything looks fine at this moment. I'll give more info as soon as we go through acceptance and production.

**Comment by sebkasanzew** [comment]
Is there a working example somewhere, how to setup `@unleash/nextjs` with GitLab?

I can't get it to work. I'm using `0.1.3-alpha.0`.

**Comment by Tymek** [comment]
@sebkasanzew 

For `v0.1.3-alpha.2` and newer:

1. In your GitLab project, go to "Deployments" > "Feature flags", click "Configure".

2. Open `.env.local` and paste details from previous step

```
UNLEASH_SERVER_URL=<API URL>
UNLEASH_SERVER_INSTANCE_ID=<Instance ID>
```

3. Use the same flag names in Gitlab and in your code.

**IMPORTANT**: GitLab provides only SERVER-SIDE API - see SSR example in this repo. You need to run _Unleash Proxy_ or _Unleash Edge_ to get Frontend API. Or you can create advanced Edge function for that (https://github.com/Unleash/unleash-client-nextjs/blob/main/example/src/pages/api/proxy-definitions.ts)

Tested with GitLab CE.
