### ISSUE TITLE
Wrong example in docs

### ISSUE THREAD

**Issue by Jax-p** [Unleash/unleash-client-nextjs#22]
## Wrong definition

Example in docs is not up to date with [types in package](https://github.com/Unleash/unleash-client-nextjs/blob/main/lib/src/evaluateFlags.ts). Docs example:
```js
const definitions = await getDefinitions();
const { toggles } = evaluateFlags(definitions); // this is wrong, second arg of evaluateFlags is typed as required Context 
```

----

## Why does SSG example use frontEnd example?
Like you know... it is server side generated.

### Subscription type

None

### Hosting type

None

**Comment by Tymek** [comment]
[`v0.1.2`](https://github.com/Unleash/unleash-client-nextjs/releases/tag/v0.1.2)
