### ISSUE TITLE
Unable to setup with CSR and GitLab instance

### ISSUE THREAD

**Issue by sebkasanzew** [Unleash/unleash-client-nextjs#44]
### Describe the bug

The unleash client doesn't get the flag information from the GitLab instance. Although the proxy in `/pages/api/feature-flags.tsx` returns a JSON with seemingly enough information and a status code 200.

Here is a codesandbox with the reproduces issue:
https://codesandbox.io/p/sandbox/unleash-nextjs-issue-44-35tcdu

You can find:
- the `<FlagProvider />` in `/pages/index.tsx`
- `useFlag` in `/components/Features.tsx`
- environment variables in `.env`

### Steps to reproduce the bug

1. Open this codesandbox: https://codesandbox.io/p/sandbox/unleash-nextjs-issue-44-35tcdu
2. The text "My feature should be visible" in `/components/Features.tsx` is not shown

### Expected behavior

The feature "my_feature" should be read and handled correctly by the unleash client and the text "My feature should be visible" should be visible.

### Additional context

Instead of an actual GitLab instance, I mocked the response of the GitLab Unleash instance in `/pages/api/feature-flags.tsx` which is als present in the real app and is used as a proxy.

### Unleash version

GitLab v15.10 (self hosted)

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

@unleash/nextjs v1.0.0

**Comment by pransh15** [comment]
Thanks for submitting this, @sebkasanzew. We'll take a look! 👀

**Comment by Tymek** [comment]
Thank you for reporting. I identified an issue. You have `data.features` instead of `data.toggles` property in the mocked response.

Correct me if I'm wrong, but I don't think GitLab is supplying Frontend API or Unleash Proxy. You need something in between of GitLab server and your frontend app. That something can be Proxy, Unleash Edge, or Next.js API route resolving toggles.

**Comment by Tymek** [comment]
Hi @sebkasanzew. Did you manage to fix this? Can I in any other way help explain differences between endpoints? Do you expect that to be in the documentation somewhere?

**Comment by sebkasanzew** [comment]
Sorry for the late response, I'm on vacation till the end of June.

I also commented wrongly where the JSON comes from. It's the result of `getDefinitions` from `@unleash/client`. So actually I don't know what the exact response from GitLab is.
So `pages/api/feature-flags.tsx` is already supposed to be my proxy-middleware for the GitLab API.

I'll try to apply your suggestions in July, when I'm fully available again.

**Comment by Tymek** [comment]
@sebkasanzew I'm closing it for now. Please reopen this or tag me in a comment if you encounter any undesired SDK behavior.
