### ISSUE TITLE
Support for custom strategies

### ISSUE THREAD

**Issue by hudovisk** [Unleash/unleash-client-nextjs#46]
### Describe the feature request

I would like to be able to use custom strategies with this sdk

### Background

We use nodejs sdk for backend feature toggle with custom strategies and would like to use the same strategies with this sdk.

### Solution suggestions

Possibility for defining custom strategies within the FlagProvider props

**Comment by Tymek** [comment]
I'm interested in what's your use case. Custom strategies can usually be translated into context fields and constraints.

**Comment by hudovisk** [comment]
Thanks, @Tymek, I was not aware of how constraints work. I got into another issue though when trying to make it work, I can open another issue if you want, but in short, I was not able to update the context in FlagProvider. During the initial render my session object is set to undefined and so are the properties in the initial context set in the `config` prop of FlagProvider. In the subsequent renders, my session is updated but the context properties remain empty (from the initial render loop).

To make it work I had to use `useUnleashContext` from `@unleash/proxy-client-react`.

**Comment by Tymek** [comment]
Opening a separate issue will be helpful.

**Comment by Tymek** [comment]
You can try new beta release (`v1.1.0-beta.0`) for `useUnleashContext`

**Comment by Tymek** [comment]
Hi @andreasdurietztibber. What I would do is adding a [Strategy Constraint](https://docs.getunleash.io/how-to/how-to-add-strategy-constraints) instead. It's free in open-source version now. If it's OK for your privacy policy to send emails in context, you can use `STR_ENDS_WITH`, but I recommend sending only _domain_ as context field. You don't need custom strategies in this simple case, or in almost any case for that matter.

**Comment by ivarconr** [comment]
Hi there, we have no immediate plans to add support for custom strategies inside our fronted SDKs. The overall plan for Unleash is to deprecate custom strategies all together from v6 of Unleash and gradually phase this out.
