### ISSUE TITLE
Broken Next.js build: Cannot destructure property 'updateContext' of null

### ISSUE THREAD

**Issue by danilofuchs** [Unleash/unleash-client-nextjs#57]
### Describe the bug

```
Error occurred prerendering page "/page". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot destructure property 'updateContext' of 'i(...)' as it is null.
    at B (file:///home/danilo/salvy/salvy-dashboard/node_modules/@unleash/proxy-client-react/dist/unleash-react.js:115:26
```

I think it refers to this line of code: https://github.com/Unleash/proxy-client-react/blob/46fa764e20617e83fd060b15f327c83cfa73fa66/src/useUnleashContext.ts#L5

### Steps to reproduce the bug

Create a Next.js project (Pages router)

Add the following provider at the _app.tsx file:

```tsx
const SessionAwareFlagContextProvider = ({
  children,
}: {
  children: ReactNode;
}) => {
  const updateContext = useUnleashContext();

  useEffect(() => {
    updateContext({
      userId: "fake-user-id",
    });
  }, [updateContext]);

  return <>{children}</>;
};
```

### Unleash version

@unleash/nextjs 1.3.0

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by Tymek** [comment]
Do you have a component using this hook wrapped with `<FlagProvider>`? A reproducible example would go a long way in solving this issue.

**Comment by Tymek** [comment]
Do you have this component wrapped in `<FlagProvider>`? @danilofuchs

**Comment by danilofuchs** [comment]
> Do you have this component wrapped in `<FlagProvider>`? @danilofuchs

Yes, it is

**Comment by danilofuchs** [comment]
The issue was, I was importing
```js
import { FlagProvider } from "@unleash/nextjs/client";
import { useUnleashContext } from "@unleash/proxy-client-react";
```

whilst the correct is to import it from the same place as FlagProvider. Probably something changed in 1.3.0 and the contexts are not the same

*CORRECT:*
```js
import { FlagProvider, useUnleashContext } from "@unleash/nextjs/client";
```
