### ISSUE TITLE
Bundlesize

### ISSUE THREAD

**Issue by astrodomas** [Unleash/unleash-client-nextjs#59]
### Describe the bug

Hello,
I've checked out `bundlephobia` for this package and found that 33% of the bundle is `semver`. Could someone explain why it is needed? 
Refer to: https://bundlephobia.com/package/@unleash/nextjs@1.3.0

![image](https://github.com/Unleash/unleash-client-nextjs/assets/134293602/f43591be-e26b-435c-99b6-f4c3e6186fce)

### Subscription type

None

### Hosting type

None

**Comment by sjaanus** [comment]
Hey there! We're using semantic versioning (`semver`) in our strategy implementation. This code is exclusively meant for backend and is not pulled into the end-user's browser.
