### ISSUE TITLE
Upgrade to unleash-client 5.5.1

### ISSUE THREAD

**Issue by danilofuchs** [Unleash/unleash-client-nextjs#64]
### Describe the bug

NPM is warning of a security issue for `ip`, which was patched in unleash-client 5.5.1

@unleash/nextjs 1.3.0 (latest published) is using pinned version 5.0.0

https://github.com/Unleash/unleash-client-node/issues/586

### Subscription type

None

### Hosting type

None

**Comment by Tymek** [comment]
Looks like vulnerable functionality of the library was never used. Fix out in `v1.4.0`
