### ISSUE TITLE
"fetch" and "abortController" missing in Next.js middleware

### ISSUE THREAD

**Issue by StillScripts** [Unleash/unleash-client-nextjs#76]
### Describe the bug

When the `flagsClient` is initiated in Next.js edge middleware, it logs two errors due to the environment. I am uncertain what impacts this has on the functionality of Unleash, but it appears that the `unleash-proxy-client` is not supported in the Next.js edge middleware environment

### Steps to reproduce the bug

1. Clone this repo and deploy the example project on Vercel.  
2. Update env variables and flags to match a specific Unleash server. 
3. Visit `/ab` 
4. View Vercel logs

### Expected behavior

I would expect to be able to pass something to the `flagsClient` to ensure that it works appropriately in Next.js edge middleware and that these error logs do not occur.

### Logs, error output, etc.

```bash
Unleash: You must either provide your own "AbortController" implementation or run in an environment where "AbortController" is available.

Unleash: You must either provide your own "fetch" implementation or run in an environment where "fetch" is available.
```

### Screenshots

![Screenshot 2024-06-03 at 1 41 09 pm](https://github.com/Unleash/unleash-client-nextjs/assets/80142739/ffd5865e-b32a-4dec-8b85-1e1a99b1351d)

### Additional context

I am new to Unleash and exploring it for AB testing at our company. Edge middleware is a requirement so that we can have minimal impact on user experience.

### Unleash version

Unleash 5.12.4

### Subscription type

None

### Hosting type

Self-hosted

### SDK information (language and version)

`"@unleash/nextjs": "^1.4.2"`

**Comment by StillScripts** [comment]
@kwasniew Thanks for looking into this. Yes, those methods seem to be available in the Edge runtime so I'm not exactly sure what would be causing the error logs. 

Yes, I have verified that the A/B tests are working fine on the site we are testing it on. So it appears that the right approach will be omitting the fetch and AbortController API checks within the Edge middleware. 

One separate issue we have is that the metrics are not being recorded in Unleash with how we are using it, but I believe this is already discussed here #50 and this is not a major issue for us as we are using external analytics providers to track this.

**Comment by kwasniew** [comment]
Correct. Next SDK server-side part does not support metrics as of today. The issue that you linked to will be updated once we come up with a solution to this.
